server:
  port: 9001

spring:
  application:
    name: cloud-alibaba-payment
  cloud:
    nacos:
      server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"