server:
  port: 8803

spring:
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment: #配置rabbimq连接环境
            spring:
              rabbitmq:
                host: localhost
                username: guest
                password: guest
      bindings:
        # 自定义：说明customOutput 和customInput 绑定到了 kylin_custom
        firstIn:
          destination: orion_first #交换机
          content-type: application/json
          group: firstGroup
        secondIn:
          destination: orion_second
          content-type: application/json
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://127.0.0.1:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: streamconsumer8803
    prefer-ip-address: true