server:
  port: 9527


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: gateway9527

spring:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: payment #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://127.0.0.1 #匹配后提供服务的路由地址
          predicates: #多种内置断言，https://docs.spring.io/spring-cloud-gateway/docs/2.2.5.RELEASE/reference/html/#the-path-route-predicate-factory
            - Path=/hystrix/feignorder/payment/** #断言,路径相匹配的进行路由
        - id: timeout
          uri: http://127.0.0.1
          predicates:
            - Path=/hystrix/feignorder/timeout/**
            - Method=GET
        - id: create
          uri: http://127.0.0.1
          predicates:
            - Path=/hystrix/feignorder/payment/create
            - Method=POST

