server:
  port: 80

logging:
  level:
    com.orion.cloud.order.feign.service.FeignOrderService: debug

eureka:
  instance:
    instance-id: feignorder80
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#参考官方配置 https://docs.spring.io/spring-cloud-openfeign/docs/2.2.5.RELEASE/reference/html/
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000