spring:
  profiles:
    active: dev
  application:
    name: cloud-hystrix-payment-service

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.orion.cloud.entities
  configuration:
    call-setters-on-nulls: false
